### ISSUE TITLE
Unable to deploy to gcloud

### ISSUE THREAD

**Issue by cgilhoi** [actions-on-google/dialogflow-name-psychic-nodejs#1]
I have been trying to deploy this to gcloud but I keep getting the same errors.  Please help!

sh: 1: functions: not found

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/nodejs/bin/node" "/nodejs/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! name-psychic@0.0.1 start: `functions deploy namePsychic --trigger-http`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the name-psychic@0.0.1 start script 'functions deploy namePsychic --trigger-http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the name-psychic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     functions deploy namePsychic --trigger-http
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs name-psychic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls name-psychic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by smishra2** [comment]
The NPM start script actually doesn't deploy to GCloud. It uses the [Google Cloud Functions Emulator](https://github.com/GoogleCloudPlatform/cloud-functions-emulator) to locally emulate the cloud function. Make sure to install it if using the start script.

**Comment by cgilhoi** [comment]
All I want to do is deploy to GCloud, not locally emulate.  Do I have to change the package.json file to make this happen?  For other projects I have used previous commits so I can deploy to Heroku without the hassle.

**Comment by arctouch-fabiolenzi** [comment]
I have the same issue (but I'm deploying to Heroku). Did you solve that?

**Comment by cgilhoi** [comment]
I ended up just copying the code over to an app that I had already deployed on Heroku and tried it again and it worked fine.  Deploying to gcloud has been nothing but problems for me.  Disappointing all of the samples now "encourage" you to use gcloud.  Heroku is WAY easier.

**Comment by Canain** [comment]
Closing this thread since we now use Firebase for our samples
