### ISSUE TITLE
Query pattern missing

### ISSUE THREAD

**Issue by Ashwin-Kapes** [actions-on-google/dialogflow-name-psychic-nodejs#10]
@Fleker  Why I'm getting this error while publishing app for Production.

**`Query pattern is missing for custom intent 'handle_permission`**

**Comment by Fleker** [comment]
Where are you seeing this error?

**Comment by Ashwin-Kapes** [comment]
@Fleker When I try to submit app for production. I get this error.

**Comment by Fleker** [comment]
Which page/console?

**Comment by Ashwin-Kapes** [comment]
When I go to this URL https://console.actions.google.com/project/my-project/release/ and click on "Submit For Production" then I get this error.

 To resolve this issue I created a backup of agent and Imported it to Newly created agent. Then it worked.
