### ISSUE TITLE
Hi @salismt,

### ISSUE THREAD

**Issue by pwreng** [actions-on-google/dialogflow-name-psychic-nodejs#12]
Hi Silvano,

I must say first I just started Firebase and Action on Google.

Apparenlty I experience the same issue. But I think I might miss a step while deploying.
Here the steps I took at deployment
In the command window
1) npm install -g firebase-tools
2) firebase login
3) firebase init functions -> Javascript -> all defaults
4) firebase functions:config:set maps.key="<THE API KEY>"
5) firebase deploy --only functions

You mentioned above, "  removing data from the associated Firebase DB", however in the firebase console, firebase DB is not in use.....What am I missing?

Thanks

_Originally posted by @silvolu in https://github.com/actions-on-google/dialogflow-name-psychic-nodejs/issues/3#issuecomment-315809297_

**Comment by Fleker** [comment]
The sample previously used Firebase DB, but between that comment and today, the sample [was updated](https://github.com/actions-on-google/dialogflow-name-psychic-nodejs/commit/a143d1cb4eeb09586a733a594adcc7c6d115ed87) to replace the DB with user storage.
