### ISSUE TITLE
multi-user compatible?

### ISSUE THREAD

**Issue by cgilhoi** [actions-on-google/dialogflow-name-psychic-nodejs#2]
Is the intention that this will work for multiple different users on the same device?  When my wife and I each just ask GH what our name are, it gets it right.  However, when she uses name psychic it gets it wrong.  Does the code need to change to support multi-users?

Thanks!

**Comment by Canain** [comment]
It should work if you have registered your voice profiles. We have docs on User Identity and the userId behavior [here](https://developers.google.com/actions/identity/user-info).

Let us know if you are still having issues.

**Comment by smishra2** [comment]
Closing since it seems there have been no further reported issues
