### ISSUE TITLE
Default welcome Intent

### ISSUE THREAD

**Issue by Ashwin-Kapes** [actions-on-google/dialogflow-name-psychic-nodejs#9]
Is it possible to comment out Default welcome Intent in index.js and let Dialogflow handle Welcome Intent. I'm getting an error when I comment out line 154-159 in index.js

Error: Dialogflow IntentHandler not found for intent:
...
...
...

**Comment by Fleker** [comment]
In Dialogflow, in your Welcome Intent, you should see a checkbox at the bottom to use the webhook for fulfillment. If you want Dialogflow to handle it, you should uncheck that.

**Comment by Ashwin-Kapes** [comment]
@Fleker It's working, but I want user entire conversation data also that need webhook to be enabled.

What I actually want is to save entire user conversation that includes user location and Name :

**Bot**: ... //Welcome Intent
**User**: ..
**Bot**: ...
**User**: ..
**Bot**: To get your location I need your permission?
**User**: yes
**Bot**: Great you are at _Mountain view, California, SF_ //(I want Lat, Lnt at backend)
**User**: ...
**Bot** ..
**User** ..
**Bot**: //End of conversation

How to achieve this? Since code in this repo focuses on Permission part only. Thanks a lot @Fleker

**Comment by Fleker** [comment]
You can toggle the fulfillment for each individual intent.

**Comment by Ashwin-Kapes** [comment]
@Fleker Why I'm getting this error while publishing app for Production env.

**`Query pattern is missing for custom intent 'handle_permission`**
